---
title: "Temp_Species_Analysis"
output: html_document
date: "2025-02-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(lubridate)
library(broom)
library(readxl)
library(tidyr)
library(anytime)
library(glue)
library(iNEXT)
library(kableExtra)
library(cowplot)
library(glmmTMB)
library(dplyr)
library(raster)
library(hillR)
library(sf)
library(tmap)
library(tidyverse)
library(leaflet)
library(ks)
library(DHARMa)
library(ggeffects)
library(performance)
library(car)
library(mgcv)
library(fitdistrplus)
library(goft)
library(gamlss)
library(vegan)
```

```{r}
dolphin <- read.csv(here("00_Raw_Data", "Dolphin_Data_2014-2024.csv"))

ww_data <- read.csv(here("00_Raw_Data", "Complete_Trip_Data_2014-2024.csv"))

GOM_shp <- st_read(dsn = here::here("00_Raw_Data/Ocean/Ocean.shp"))

```

```{r}

dolphin <- dolphin %>%
  filter(!is.na(Latitude),
         Latitude != 0,
         Longitude <= -65,
         Latitude != 45.10,
         Latitude != 44.99,
         Latitude != 44.90,
         Latitude != 44.80,
         TripKey != 766,
         TripKey != 299,
         Surface.Temp..C. != 0.0)

dolphin$Longitude <- abs(dolphin$Longitude) 
dolphin$Longitude <- (dolphin$Longitude)* -1

all_ww <- dolphin %>%
  full_join(ww_data)

all_ww$date <- dmy(all_ww$dDate)
all_ww$year <- year(all_ww$date)
all_ww$month <- month(all_ww$date)

all_ww <- all_ww %>%
  mutate(dolphin_presence = case_when(Species %in% c("La", "Tt", "Dd", "Lal", "Gg", "Pp") ~ 1,
                                       is.na(Species) ~ 0)) %>%
  filter(!is.na(date))

dolphin_clean <- all_ww %>%
  filter(dolphin_presence == 1)

dolphin_clean$year_month <- paste(dolphin_clean$year, dolphin_clean$month, "01",sep = "-")
dolphin_clean$year_month <- as.Date(dolphin_clean$year_month)
```
```{r standardizing by year}
dolphins_standardized_year <- all_ww %>%
  group_by(year) %>%
  summarize(total_trips = n(),
            trips_w_dolphin = sum(dolphin_presence),
            percentage = (trips_w_dolphin/total_trips)*100) %>%
  mutate(
    percentage_standardized = scale(percentage))
```

```{r}
dolphins_year_graph <- dolphins_standardized_year %>%
  ggplot(mapping = aes(x = year, y = percentage)) +
  geom_point() +
  geom_smooth() +
  theme_classic() +
  scale_x_continuous(breaks = seq(min(dolphins_standardized_year$year), 
                                  max(dolphins_standardized_year$year), 
                                  by = 1))
dolphins_year_graph

ggsave(plot = dolphins_year_graph, filename = here("Figures_Tables", "dolphins_year.png"), width = 7.5, height = 5.5, 
    units = "in", pointsize = 15, dpi = 220)
```


```{r standardizing by species}

dolphins_standardized_month <- all_ww %>%
  group_by(year, month) %>%
  summarize(total_trips = n(),
            trips_w_dolphin = sum(dolphin_presence),
            percentage = (trips_w_dolphin/total_trips)*100) %>%
  mutate(
    percentage_standardized = scale(percentage))

dolphins_standardized_month$year_month <- paste(dolphins_standardized_month$year, dolphins_standardized_month$month, "01",sep = "-")
dolphins_standardized_month$year_month <- as.Date(dolphins_standardized_month$year_month)

temperature <- all_ww %>%
  filter(!is.na(Surface.Temp..C.),
         TripKey != 766,
         TripKey != 299,
         Surface.Temp..C. != 0.0) %>%
  group_by(year, month) %>%
  summarize(mean_SST = mean(Surface.Temp..C.),
             se = sd(Surface.Temp..C., na.rm = TRUE) / sqrt(length(Surface.Temp..C.[!is.na(Surface.Temp..C.)])))

temperature$year_month <- paste(temperature$year, temperature$month, "01",sep = "-")
temperature$year_month <- as.Date(temperature$year_month)

dolphins_standardized_month <- dolphins_standardized_month %>%
  full_join(dolphin_clean) %>%
  left_join(temperature) 

dolphins_standardized_month <- dolphins_standardized_month %>%
  filter(!is.na(TripKey)) %>%
  dplyr::select(year, month, total_trips, trips_w_dolphin, percentage, year_month, dDate, Surface.Temp..C., mean_SST, Species)

```

```{r percentage of sightings with dolphins by month}
dolphins_month_graph <- 
  ggplot() +
    geom_point(data = dolphins_standardized_month, mapping = aes(x = year_month, y = percentage), colour = "blue") +
  geom_smooth(data = dolphins_standardized_month, mapping = aes(x = year_month, y = percentage), colour = "blue") +
  geom_point(data = temperature, mapping = aes(x = year_month, y = (mean_SST)), colour = "red") +
  geom_smooth(data = temperature, mapping = aes(x = year_month, y = (mean_SST)), colour = "red") +
   scale_y_continuous(
    name = "Percentage of whale watch trips with\n dolphin sightings (%)",
    sec.axis = sec_axis(~ . / 1, name = "Temperature (°C)")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  scale_x_date(date_labels = "%Y-%m", date_breaks = "6 months") +
  labs(x = "Year and month", y = "Percentage of whale watch trips with\n dolphin sightings (%)")
  
dolphins_month_graph

ggsave(plot = dolphins_month_graph, filename = here("Figures_Tables", "dolphins_month.png"), width = 7.5, height = 5.5, 
    units = "in", pointsize = 15, dpi = 220)
```
```{r percentage vs temp}
dolphins_standardized_month %>%
  ggplot(mapping = aes(x = mean_SST, y = percentage)) +
  geom_point() +
  geom_smooth(method = lm, color = "black")
  theme_classic()
```

```{r models}
#linear: fits but not significant

dolphin.lm <- lm(percentage ~ Species + Surface.Temp..C., 
             data = dolphins_standardized_month)

summary(dolphin.lm)

vif(dolphin.lm)

plot(simulateResiduals(dolphin.lm))

#gaussian: fits but not significant

dolphin.gaussian <- glmmTMB(percentage ~ Species + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = gaussian(link = "identity"))

dolphin.gaussian.residuals <- simulateResiduals(dolphin.gaussian)
plot(dolphin.gaussian.residuals)

summary(dolphin.gaussian)

#Gamma: fits but not significant

dolphin.gamma <- glmmTMB(percentage ~ Species + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = Gamma(link = "inverse"))

dolphin.gamma.residuals <- simulateResiduals(dolphin.gamma)
plot(dolphin.gamma.residuals)

summary(dolphin.gamma)

#inverse.gaussian: fits but not significant
dolphin.inv.gaussian <- glmmTMB(percentage ~ Species + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = inverse.gaussian(link = "1/mu^2"))

dolphin.inv.gaussian.residuals <- simulateResiduals(dolphin.inv.gaussian)
plot(dolphin.inv.gaussian.residuals)

summary(dolphin.inv.gaussian)

#poisson: NO

dolphin.poisson <- glmmTMB(percentage ~ Species + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = poisson(link = "log"))

dolphin.poisson.residuals <- simulateResiduals(dolphin.poisson)
plot(dolphin.poisson.residuals)

#quasi: NO

#dolphin.quasi <- glmmTMB(percentage ~ Species + Surface.Temp..C.,
     #                  data = dolphins_standardized_month,
      #                 family = quasi("identity", variance = "constant"))

#dolphin.quasi.residuals <- simulateResiduals(dolphin.poisson)
#plot(dolphin.quasi.residuals)

#quasi poisson: No
#dolphin.quasi.poisson <- glmmTMB(percentage ~ Species + Surface.Temp..C.,
 #                      data = dolphins_standardized_month,
 #                      family = quasipoisson(link = "log"))

#dolphin.quasi.poisson.residuals <- simulateResiduals(dolphin.quasi.poisson)
#plot(dolphin.quasi.poisson.residuals)

#Skewnormal distribution: NO
#dolphin.skewnorm <- glmmTMB(percentage ~ Species + Surface.Temp..C.,
#                       data = dolphins_standardized_month,
 #                      family = skewnormal(link = "identity"))
#dolphin.skewnorm.residuals <- simulateResiduals(dolphin.skewnorm)
#plot(dolphin.skewnorm.residuals)

#Lognormal distribution: NO
dolphin.lognormal <- glmmTMB(percentage ~ Species + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = lognormal(link = "log"))
dolphin.lognormal.residuals <- simulateResiduals(dolphin.lognormal)
plot(dolphin.lognormal.residuals)

#t_family distribution: fits but not significant
dolphin.tfam <- glmmTMB(percentage ~ Species + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = t_family(link = "identity"))
dolphin.tfam.residuals <- simulateResiduals(dolphin.tfam)
plot(dolphin.tfam.residuals)

summary(dolphin.tfam)

#negative binomial
#dolphin.nbinom1 <- glmmTMB(percentage ~ Species + Surface.Temp..C.,
#                       data = dolphins_standardized_month,
#                       family = nbinom1(link = "log"))
#dolphin.nbinom1.residuals <- simulateResiduals(dolphin.nbinom1)
#plot(dolphin.nbiom1.residuals)
```
```{r}
#linear: NO

month.lm <- lm(percentage ~ month + Surface.Temp..C., 
             data = dolphins_standardized_month)

summary(month.lm)

vif(month.lm)

plot(simulateResiduals(month.lm))

#gaussian: No

month.gaussian <- glmmTMB(percentage ~ month + Surface.Temp..C., 
                       data = dolphins_standardized_month,
                       family = gaussian(link = "identity"))

month.gaussian.residuals <- simulateResiduals(month.gaussian)
plot(month.gaussian.residuals)

#Gamma: No

month.gamma <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = Gamma(link = "inverse"))

month.gamma.residuals <- simulateResiduals(month.gamma)
plot(month.gamma.residuals)

#inverse.gaussian: fits but not significant
month.inv.gaussian <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = inverse.gaussian(link = "1/mu^2"))

month.inv.gaussian.residuals <- simulateResiduals(month.inv.gaussian)
plot(month.inv.gaussian.residuals)

#poisson: NO

month.poisson <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = poisson(link = "log"))

month.poisson.residuals <- simulateResiduals(month.poisson)
plot(month.poisson.residuals)

#Lognormal distribution: NO
month.lognormal <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = lognormal(link = "log"))
month.lognormal.residuals <- simulateResiduals(month.lognormal)
plot(month.lognormal.residuals)

#t_family distribution: NO
month.tfam <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = t_family(link = "identity"))
month.tfam.residuals <- simulateResiduals(month.tfam)
plot(month.tfam.residuals)

#negative binomial1: No
#month.nbinom1 <- glmmTMB(percentage ~ month + #Surface.Temp..C.,
#                       data = dolphins_standardized_month,
#                       family = nbinom1(link = "log"))
#month.nbinom1.residuals <- simulateResiduals(month.nbinom1)
#plot(month.nbiom1.residuals)

#compois: No
month.compois <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = compois(link = "log"))
month.compois.residuals <- simulateResiduals(month.compois)
plot(month.compois.residuals)

#truncated compois: No
month.trunccompois <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = truncated_compois(link = "log"))
month.trunccompois.residuals <- simulateResiduals(month.trunccompois)
plot(month.trunccompois.residuals)

#gen pois: No
month.genpois <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = genpois(link = "log"))
month.genpois.residuals <- simulateResiduals(month.genpois)
plot(month.genpois.residuals)

#truncated gen pois: No
month.truncgenpois <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = truncated_genpois(link = "log"))
month.truncgenpois.residuals <- simulateResiduals(month.truncgenpois)
plot(month.truncgenpois.residuals)

#truncated poisson: No
month.truncpoiss <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = truncated_poisson(link = "log"))
month.truncpoiss.residuals <- simulateResiduals(month.truncpoiss)
plot(month.truncpoiss.residuals)

#tweedie: No
month.tweedie <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = tweedie(link = "log"))
month.tweedie.residuals <- simulateResiduals(month.tweedie)
plot(month.tweedie.residuals)

#zigamma: No
month.zigamma <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = dolphins_standardized_month,
                       family = ziGamma(link = "inverse"))
month.zigamma.residuals <- simulateResiduals(month.zigamma)
plot(month.zigamma.residuals)

#Gam distributions

mSShash <- histDist(dolphins_standardized_month$percentage, "SHASH", density = T, main = "Shash")
#mSBe <- histDist(dolphins_standardized_month$percentage, "BE", density = T, main = "Beta") 
#mSDPo <- histDist(dolphins_standardized_month$percentage, "DPO", density = T, main = "Double Poisson") 
#mSDel <- histDist(dolphins_standardized_month$percentage, "DEL", density = T, main = "Delaport")
#mSGa <- histDist(dolphins_standardized_month$percentage, "GA", density = T, main = "Gamma") 
mSGenGa <- histDist(dolphins_standardized_month$percentage, "GG", density = T, main = "Gen Gamma")
#mSGig <- histDist(dolphins_standardized_month$percentage, "GIG", density = T, main = "Gen Inverse Gaussian") 
mSGum <- histDist(dolphins_standardized_month$percentage, "GU", density = T, main = "Gumbel") 
#mSIGam <- histDist(dolphins_standardized_month$percentage, "IGAMMA", density = T, main = "Inverse Gamma")
#mSIG <- histDist(dolphins_standardized_month$percentage, "IG", density = T, main = "Inverse Gaussian")
mSJSU <- histDist(dolphins_standardized_month$percentage, "JSU", density = T, main = "Johnsons SU")
#mSLoga <- histDist(dolphins_standardized_month$percentage, "LG", density = T, main = "Logarithmic")
mSLogi <- histDist(dolphins_standardized_month$percentage, "LO", density = T, main = "Logistic") 
#mSLogitNo <- histDist(dolphins_standardized_month$percentage, "LOGITNO", density = T, main = "Logit-Normal")
#mSLoNorm <- histDist(dolphins_standardized_month$percentage, "LOGNO", density = T, main = "Log-normal")
#mSLNoBox <- histDist(dolphins_standardized_month$percentage, "LNO", density = T, main = "Log-normal Box COx")
mSNorm <- histDist(dolphins_standardized_month$percentage, "NO", density = T, main = "Normal")
mSNormFam <- histDist(dolphins_standardized_month$percentage, "NOF", density = T, main = "Normal Family") 
mSLQNO <- histDist(dolphins_standardized_month$percentage, "LQNO", density = T, main = "Normal Linear Quad")
#mSPa <- histDist(dolphins_standardized_month$percentage, "PARETO2", density = T, main = "Pareto2") 
#mSPoi <- histDist(dolphins_standardized_month$percentage, "PO", density = T, main = "Poisson")
#mSPIG <- histDist(dolphins_standardized_month$percentage, "PIG", density = T, main = "Poisson Inv Gaussian")
#mSReGE <- histDist(dolphins_standardized_month$percentage, "RGE", density = T, main = "Rev Gen Extreme")
mSRevGum <- histDist(dolphins_standardized_month$percentage, "RG", density = T, main = "Reverse Gumbel")
mShaOG <- histDist(dolphins_standardized_month$percentage, "SHASHo", density = T, main = "Shash OG")
mSSich <- histDist(dolphins_standardized_month$percentage, "SICHEL", density = T, main = "Sichel")
#mSSimp <- histDist(dolphins_standardized_month$percentage, "SIMPLEX", density = T, main = "Simplex")
mSSkewT1 <- histDist(dolphins_standardized_month$percentage, "ST1", density = T, main = "Skew Type 1")
mSSkewT2 <- histDist(dolphins_standardized_month$percentage, "ST2", density = T, main = "Skew Type 2")
mSSkewT3 <- histDist(dolphins_standardized_month$percentage, "ST3", density = T, main = "Skew Type 3")
mSSkewT4 <- histDist(dolphins_standardized_month$percentage, "ST4", density = T, main = "Skew Type 4")
mSSkewT5 <- histDist(dolphins_standardized_month$percentage, "ST5", density = T, main = "Skew Type 5")
mST <- histDist(dolphins_standardized_month$percentage, "TF", density = T, main = "T distribution")
#mSWa <- histDist(dolphins_standardized_month$percentage, "WARING", density = T, main = "Waring")
mSWeeb <- histDist(dolphins_standardized_month$percentage, "WEI", density = T, main = "Weibull")

GAIC(mSShash, mSGenGa, mSGum, mSJSU, mSLogi, mSNorm, mSNormFam, mSLQNO, mSRevGum, mShaOG, mSSich, mSSkewT1, mSSkewT2, mSSkewT3, mSSkewT4, mSSkewT5, mST, mSWeeb)



month.GG.mod <- gamlss(percentage ~ month + Surface.Temp..C., 
               family = GG(), 
               data = dolphins_standardized_month)

summary(month.GG.mod)
month.GG.residuals <- residuals(month.GG.mod)
plot(month.GG.residuals)
plot(month.GG.mod)
```

```{r}

#all dolphin percent month graph
dolph_percent_month <- ggplot(data = dolphins_standardized_month,
                         aes(x = month, y = percentage)) +
  geom_point() +
  geom_smooth(method = "gam", color = "black") +
  theme_classic() +
  labs(x = "month", y = "Percentage of trips with dolphin sightings (%)")

dolph_percent_month

ggsave(plot = dolph_percent_month,
       filename = here("Figures_Tables", "dolph_percent_month.png"),
       height = 7, width = 14, units = "cm")

#all dolphin percent temp graph
dolph_percent_temp <- ggplot(data = dolphins_standardized_month,
                         aes(x = Surface.Temp..C., y = percentage)) +
  geom_point() +
  geom_smooth(method = "gam", color = "black") +
  theme_classic() +
  labs(x = "Sea Surface Temperature (C)", y = "Percentage of trips with dolphin sightings (%)")

dolph_percent_temp

ggsave(plot = dolph_percent_temp,
       filename = here("Figures_Tables", "dolph_percent_temp.png"),
       height = 7, width = 14, units = "cm")

#dolphin percent month year graph
dolph_percent_year_month <- ggplot(data = dolphins_standardized_month,
                         aes(x = year_month, y = percentage)) +
  geom_point() +
  geom_smooth(method = "gam", color = "black") +
  theme_classic() +
  labs(x = "Month and year", y = "Percentage of trips with dolphin sightings (%)")

dolph_percent_year_month

ggsave(plot = dolph_percent_year_month,
       filename = here("Figures_Tables", "dolph_percent_year_month.png"),
       height = 7, width = 14, units = "cm")
```

```{r}
white_sided <- dolphins_standardized_month %>%
  filter(Species == "La")
```

```{r}
#linear: NO

ws.lm <- lm(percentage ~ month + Surface.Temp..C., 
             data = white_sided)

summary(ws.lm)

vif(ws.lm)

plot(simulateResiduals(ws.lm))

#gaussian: No

ws.gaussian <- glmmTMB(percentage ~ month + Surface.Temp..C., 
                       data = white_sided,
                       family = gaussian(link = "identity"))

ws.gaussian.residuals <- simulateResiduals(ws.gaussian)
plot(ws.gaussian.residuals)

#Gamma: No

ws.gamma <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = white_sided,
                       family = Gamma(link = "inverse"))

ws.gamma.residuals <- simulateResiduals(ws.gamma)
plot(ws.gamma.residuals)

#inverse.gaussian: fits but not significant
ws.inv.gaussian <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = white_sided,
                       family = inverse.gaussian(link = "1/mu^2"))

ws.inv.gaussian.residuals <- simulateResiduals(ws.inv.gaussian)
plot(ws.inv.gaussian.residuals)

#poisson: NO

ws.poisson <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = white_sided,
                       family = poisson(link = "log"))

ws.poisson.residuals <- simulateResiduals(ws.poisson)
plot(ws.poisson.residuals)

#Lognormal distribution: NO
ws.lognormal <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = white_sided,
                       family = lognormal(link = "log"))
ws.lognormal.residuals <- simulateResiduals(ws.lognormal)
plot(ws.lognormal.residuals)

#t_family distribution: fits but not significant
ws.tfam <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = white_sided,
                       family = t_family(link = "identity"))
ws.tfam.residuals <- simulateResiduals(ws.tfam)
plot(ws.tfam.residuals)

#negative binomial1: No
#ws.nbinom1 <- glmmTMB(percentage ~ month + Surface.Temp..C.,
#                       data = white_sided,
#                       family = nbinom1(link = "log"))
#ws.nbinom1.residuals <- simulateResiduals(ws.nbinom1)
#plot(ws.nbiom1.residuals)

#compois: No
ws.compois <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = white_sided,
                       family = compois(link = "log"))
ws.compois.residuals <- simulateResiduals(ws.compois)
plot(ws.compois.residuals)

#truncated compois: No
ws.trunccompois <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = white_sided,
                       family = truncated_compois(link = "log"))
ws.trunccompois.residuals <- simulateResiduals(ws.trunccompois)
plot(ws.trunccompois.residuals)

#gen pois: No
ws.genpois <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = white_sided,
                       family = genpois(link = "log"))
ws.genpois.residuals <- simulateResiduals(ws.genpois)
plot(ws.genpois.residuals)

#truncated gen pois: No
ws.truncgenpois <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = white_sided,
                       family = truncated_genpois(link = "log"))
ws.truncgenpois.residuals <- simulateResiduals(ws.truncgenpois)
plot(ws.truncgenpois.residuals)

#truncated poisson: No
ws.truncpoiss <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = white_sided,
                       family = truncated_poisson(link = "log"))
ws.truncpoiss.residuals <- simulateResiduals(ws.truncpoiss)
plot(ws.truncpoiss.residuals)

#tweedie: No
ws.tweedie <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = white_sided,
                       family = tweedie(link = "log"))
ws.tweedie.residuals <- simulateResiduals(ws.tweedie)
plot(ws.tweedie.residuals)

#zigamma: No
ws.zigamma <- glmmTMB(percentage ~ month + Surface.Temp..C.,
                       data = white_sided,
                       family = ziGamma(link = "inverse"))
ws.zigamma.residuals <- simulateResiduals(ws.zigamma)
plot(ws.zigamma.residuals)

#Gam distributions

ws_mSShash <- histDist(white_sided$percentage, "SHASH", density = T, main = "Shash")
#ws_mSBe <- histDist(white_sided$percentage, "BE", density = T, main = "Beta") 
#ws_mSDPo <- histDist(white_sided$percentage, "DPO", density = T, main = "Double Poisson") 
#ws_mSDel <- histDist(white_sided$percentage, "DEL", density = T, main = "Delaport")
#ws_mSGa <- histDist(white_sided$percentage, "GA", density = T, main = "Gamma") 
ws_mSGenGa <- histDist(white_sided$percentage, "GG", density = T, main = "Gen Gamma")
ws_mSGig <- histDist(white_sided$percentage, "GIG", density = T, main = "Gen Inverse Gaussian") 
ws_mSGum <- histDist(white_sided$percentage, "GU", density = T, main = "Gumbel") 
#ws_mSIGam <- histDist(white_sided$percentage, "IGAMMA", density = T, main = "Inverse Gamma")
#ws_mSIG <- histDist(white_sided$percentage, "IG", density = T, main = "Inverse Gaussian")
ws_mSJSU <- histDist(white_sided$percentage, "JSU", density = T, main = "Johnsons SU")
ws_mSLoga <- histDist(white_sided$percentage, "LG", density = T, main = "Logarithmic")
ws_mSLogi <- histDist(white_sided$percentage, "LO", density = T, main = "Logistic") 
#ws_mSLogitNo <- histDist(white_sided$percentage, "LOGITNO", density = T, main = "Logit-Normal")
#ws_mSLoNorm <- histDist(white_sided$percentage, "LOGNO", density = T, main = "Log-normal")
#ws_mSLNoBox <- histDist(white_sided$percentage, "LNO", density = T, main = "Log-normal Box COx")
ws_mSNorm <- histDist(white_sided$percentage, "NO", density = T, main = "Normal")
ws_mSNormFam <- histDist(white_sided$percentage, "NOF", density = T, main = "Normal Family")
ws_mSLQNO <- histDist(white_sided$percentage, "LQNO", density = T, main = "Normal Linear Quad")
#ws_mSPa <- histDist(white_sided$percentage, "PARETO2", density = T, main = "Pareto2")
#ws_mSPoi <- histDist(white_sided$percentage, "PO", density = T, main = "Poisson")
#ws_mSPIG <- histDist(white_sided$percentage, "PIG", density = T, main = "Poisson Inv Gaussian")
ws_mSReGE <- histDist(white_sided$percentage, "RGE", density = T, main = "Rev Gen Extreme")
#ws_mSRevGum <- histDist(white_sided$percentage, "RG", density = T, main = "Reverse Gumbel")
ws_mShaOG <- histDist(white_sided$percentage, "SHASHo", density = T, main = "Shash OG")
#ws_mSSich <- histDist(white_sided$percentage, "SICHEL", density = T, main = "Sichel")
#ws_mSSimp <- histDist(white_sided$percentage, "SIMPLEX", density = T, main = "Simplex")
ws_mSSkewT1 <- histDist(white_sided$percentage, "ST1", density = T, main = "Skew Type 1")
ws_mSSkewT2 <- histDist(white_sided$percentage, "ST2", density = T, main = "Skew Type 2")
ws_mSSkewT3 <- histDist(white_sided$percentage, "ST3", density = T, main = "Skew Type 3")
ws_mSSkewT4 <- histDist(white_sided$percentage, "ST4", density = T, main = "Skew Type 4")
ws_mSSkewT5 <- histDist(white_sided$percentage, "ST5", density = T, main = "Skew Type 5")
ws_mST <- histDist(white_sided$percentage, "TF", density = T, main = "T distribution")
#ws_mSWa <- histDist(white_sided$percentage, "WARING", density = T, main = "Waring")
ws_mSWeeb <- histDist(white_sided$percentage, "WEI", density = T, main = "Weibull")

GAIC(ws_mSShash, ws_mSGenGa, ws_mSGig, ws_mSGum, ws_mSJSU, ws_mSLoga, ws_mSLogi, ws_mSNorm, ws_mSNormFam, ws_mSLQNO, ws_mSReGE, ws_mShaOG, ws_mSSkewT1, ws_mSSkewT2, ws_mSSkewT3, ws_mSSkewT4, ws_mSSkewT5, ws_mST, ws_mSWeeb)

ws.ShaOG.mod <- gamlss(percentage ~ month + Surface.Temp..C., 
               family = SHASHo(), 
               data = white_sided)

summary(ws.ShaOG.mod)
plot(ws.ShaOG.mod)
ws.ShaOG.residuals <- residuals(ws.ShaOG.mod)
plot(ws.ShaOG.residuals)
```
```{r}
#white sided dolphin percent month graph
ws_percent_month <- ggplot(data = white_sided,
                         aes(x = month, y = percentage)) +
  geom_point() +
  geom_smooth(method = "gam", color = "black") +
  theme_classic() +
  labs(x = "month", y = "Percentage of trips with white sided dolphin sightings (%)")

ws_percent_month

ggsave(plot = ws_percent_month,
       filename = here("Figures_Tables", "ws_percent_month.png"),
       height = 7, width = 14, units = "cm")

#white sided dolphin percent temp graph
ws_percent_temp <- ggplot(data = white_sided,
                         aes(x = Surface.Temp..C., y = percentage)) +
  geom_point() +
  geom_smooth(method = "gam", color = "black") +
  theme_classic() +
  labs(x = "Sea Surface Temperature (C)", y = "Percentage of trips with white sided dolphin sightings (%)")

ws_percent_temp

ggsave(plot = ws_percent_temp,
       filename = here("Figures_Tables", "ws_percent_temp.png"),
       height = 7, width = 14, units = "cm")

#white sided dolphin percent month year graph
ws_percent_year_month <- ggplot(data = white_sided,
                         aes(x = year_month, y = percentage)) +
  geom_point() +
  geom_smooth(method = "gam", color = "black") +
  theme_classic() +
  labs(x = "Month and year", y = "Percentage of trips with white sided dolphin sightings (%)")

ws_percent_year_month

ggsave(plot = ws_percent_year_month,
       filename = here("Figures_Tables", "ws_percent_year_month.png"),
       height = 7, width = 14, units = "cm")

```

